version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - mysql    
    env_file:
      - backend/.env.dev
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - ./backend/.env.dev:/var/www/html/.env
    ports:
      - "8000:80"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0

volumes:
  mysql_data:
